### ISSUE TITLE
Clockwise drawing of polygon fails + cannot close polygon on Windows + Chrome

### ISSUE THREAD

**Issue by z0d14c** [Leaflet/Leaflet.draw#637]
May be related to https://github.com/Leaflet/Leaflet.draw/issues/563 although that appears to be occurring on IE11.

Basically the issue we're having is that on someone's Windows 8.x + Chrome (latest version) box, the closing of polygons is very difficult (it appears that you have to click on the center pixel instead of any pixel in the draw handle) and drawing them clockwise is impossible (leaflet.draw says there is an intersection when there isn't). 

I will be testing this further and trying to come up with a fix, but if someone more intimately involved with Leaflet.draw thinks they can do it faster don't let me stop you.

**Comment by z0d14c** [comment]
Reproduced on windows + edge as well.

**Comment by z0d14c** [comment]
It appears that #563 does indeed fix the issue for us. Can @Smeats solution not be merged into this project?

**Comment by B3nCr** [comment]
It's also related to this https://github.com/Leaflet/Leaflet.draw/issues/631 and this  https://github.com/Leaflet/Leaflet.draw/issues/624.

It seems to me as if this is becoming a major issue.

I've fixed this another way in another PR. I haven't tested @Smeats fix so I don;t know what affect that has on the touch events. 

Please can you test this and see if it does what you need https://b3ncr.github.io/docs/examples/full.html

My PR is here, I may re-create it because it has an unnecessary change in there but if I take it out the github.io page will break. https://github.com/Leaflet/Leaflet.draw/pull/636

**Comment by z0d14c** [comment]
@B3nCr  It does appear to fix the issues, in maybe a cleaner way than @Smeats'. We may fork your branch until this is cleared up (i.e. merged into Leaflet.draw master). Thanks for looking into this, I'll try to remain actively pushing to get attention for this bug as it is pretty bad for many users.

**Comment by z0d14c** [comment]
strangely, Leaflet.draw 0.4.7 does not seem to fix the issues for me, although my branch of b3nCr's branch does. im not sure why this is the case.

**Comment by robinho81** [comment]
I can concur that I am experiencing the same problem on Leaflet.draw 0.4.7. 

Environment is:
Windows 10 Pro
Chrome Version 55.0.2883.75
(Also worthwhile noting that I am using a Laptop with Touch Screen connected to a normal monitor)

 A while back I commented on issue #624 and mentioned that a work around was to turn touch events off in Chrome. Unfortunately, it seems that this workaround no longer works and I still get the issue in Chrome regardless of whether I have touch enabled or not in the flags. This is somewhat unfortunate.

**Comment by z0d14c** [comment]
forgot to leave a comment after I discovered new information -- here's my comment from B3nCr's PR: 

> Yeah, I'm pretty sure that regresses your fix, workaround or no, which basically renders IE/Android/iOS unusable for the respectively bugged draw shapes. I'll see if I can take a look at working on a PR this week as I'd like to continue using the main repo, but we'll see. @B3nCr

Basically it looks like Leaflet.draw 0.4.7 promptly regressed B3nCr's fix, and we likely need more tests to address this situation.

**Comment by z0d14c** [comment]
i have a PR up to address some of these issues, further testing needed on IE because i think touchstart events may need some special handling in that context (and my IE VM was running extremely slow)

**Comment by ddproxy** [comment]
Thanks for the PR, I'll review after I land.

This seems to have occurred on Chrome 55.x on Mac as well.

**Comment by z0d14c** [comment]
I think theres one small addition thats needed, which is binding only the
touch or the mouseclick event binding in addHooks, depending on
L.Browser.touch, in order for IE to work correctly (duplicate events are
messing things up)

**Comment by z0d14c** [comment]
I believe my PR fixes all of these issues https://github.com/Leaflet/Leaflet.draw/pull/657

**Comment by jedfong** [comment]
I've seen a similar issue when L.Browser.touch is disabled (leaflet v1.0.2 / leaflet-draw v0.4.9).  Polylines/Polygons will not close.  The problem goes away if I comment out the following line in addHooks (L.Draw.Polyline):

`.on('touchstart', this._onTouch, this)`

Maybe this should be conditional based on if touch is enabled/disabled?
