### ISSUE TITLE
Unable to cancel Rectangle and Circle drawing in Chrome w/Touch

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet.draw#922]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: `1.4`
- Leaflet Draw version I'm using: `1.0.4`
- Browser (with version) I'm using: `Chrome Version 73.0.3683.103`
- OS/Platform (with version) I'm using: `Windows 10 32-bit`

Actually I suffer from this issue on android, but it's easy to reproduce it on Chrome on desktop.
1. Open Chrome DevTools <kbd>Ctrl-Shift-I</kbd> and enter mobile mode <kbd>Ctrl-Shift-M</kbd>
2. Press Rectangle creating button.

## What behaviour I'm expecting and which behaviour I'm seeing

It's now impossible to exit drawing mode, because neither toolbar nor tooltip are clickable.
We can exit only finishing rectangle.
There are also issues with multiple taps.
Circle has the same issue

I found another mobile-related issue here: #789

## Minimal example reproducing the issue

Official sample is enough:
https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

**Comment by berniesf** [comment]
This morning researching a little bit... I found the click event works only inside the map._panes.overlayPane when the browser is in mobile mode.


`polygonDrawer = new L.Draw.Rectangle(map, polygon_query_options);`
`polygonDrawer.enable();`
`var panes=map._panes.overlayPane;`
`$(panes).append('<button id="cButton" class="buttons" type="button" style="top:90px" onclick="cancelpoly()">CANCEL</button>');`

`      function cancelpoly() {
         if (polygonDrawer != undefined) { polygonDrawer.disable(); }
      };`

This will create a button and cancel the rectangle drawing. I hope this serves as a clue to fix the problem.

**Comment by berniesf** [comment]
I found a solution. The line 1260 of the leaflet.draw 1.0.4 contains the following code:

`document.addEventListener('touchstart', L.DomEvent.preventDefault, { passive: false });`

I replaced that line with 

`var tempMap = document.getElementById("map");`
`tempMap.addEventListener('touchstart', L.DomEvent.preventDefault, { passive: false });`

Basically instead of preventing the touchstart event on the document, now is applied only to the map object.

**Comment by johnd0e** [comment]
@berniesf 
Thanks, it's working now!
(if repeat the same step with the `removeEventListener`)

One more issue left: 'Cancel' button is still non clickable.

**Comment by johnd0e** [comment]
Thanks!
Actually this works for me:
```
			this._map.getPane('mapPane').addEventListener('touchstart', L.DomEvent.preventDefault, {passive: false});
```

And then:
```
			this._map.getPane('mapPane').removeEventListener('touchstart', L.DomEvent.preventDefault);
```

**Comment by berniesf** [comment]
@johnd0e glad to help pinpointing the source of the problem :)

**Comment by berniesf** [comment]
@johnd0e after some test this morning, I found your code works but only on the second try. Let me explain. I clicked on the create poly button, when I start dragging to create a rectangle, touchend fires immediately and stops the drawing (behaves like when passive is turned on). If I click a second time on the create poly button, it works.

With my code (applying addEventListener to elementID 'map') it works at the first shot. 

Are you using the leaflet.draw UI to draw objects? I'm not using it on my project.

**Comment by johnd0e** [comment]
> Are you using the leaflet.draw UI to draw objects?

I use leaflet.draw toolbar.

> With my code (applying addEventListener to elementID 'map') it works at the first shot.

With your code whole map get blocked, including draw toolbar, that's why I add listener on map pane only.
Also you do not remove event listener (in your sample code), so whole map with all controls stays blocked even after I finished drawing.

> I clicked on the create poly button, when I start dragging to create a rectangle,

Is it poly or rectangle?

**Comment by berniesf** [comment]
> Is it poly or rectangle?

rectangle.

> Also you do not remove event listener (in your sample code),

Yes, I forgot to remove the event. Thanks to your code I realized that. Now its fixed

Since I'm not using the UI (or toolbar), I get the desired result. I wonder if a mixed solution can be made, since some people uses leaflet.draw without the toolbar (judging by posted questions on stackoverflow).

**Comment by johnd0e** [comment]
> when I start dragging to create a rectangle, touchend fires immediately and stops the drawing (behaves like when passive is turned on). If I click a second time on the create poly button, it works.

Have you figured out why `touchend` fires only during first time drawing? It's weird.

**Comment by berniesf** [comment]
I haven't found what is the source of that behavior, but I came with this:

`var obj = (document.getElementsByClassName("leaflet-draw-section").length) ? this._map.getPane('mapPane') : this._map._container;`
`obj.addEventListener('touchstart', L.DomEvent.preventDefault, { passive: false });`

this checks for toolbox, if not found returns the map. Covers both usage scenarios.

**Comment by johnd0e** [comment]
It's also terrible..

But it seems I've found more clean workaround: just add `#map { touch-action: none; }` to your css, ~~and you do not need this PR.~~ and you can completely delete those code lines with `addEventListener`/`removeEventListener`.

**Comment by berniesf** [comment]
It looks like touch-action is not supported on desktop safari, and partially supported on iOS... maybe the JS is still a good solution?

[https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action](url)

**Comment by johnd0e** [comment]
May be.
And may be better switch to https://github.com/Leaflet/Leaflet.Editable

**Comment by johnd0e** [comment]
Original issue is not reproduced anymore with new Leaflet 1.6.
(Perhaps fixed by https://github.com/Leaflet/Leaflet/pull/6694)

BTW, these lines are not required now as well: https://github.com/Leaflet/Leaflet.draw/blob/d5dd11781c2e07f9e719308e504fe579000edf54/src/draw/handler/Draw.SimpleShape.js#L41-L47

**Comment by iisri-vu** [comment]
This problem still existed with Leaflet 1.7.1.
We can not press the cancel button when drawing a circle.    But we can press the cancel button when drawing a polygon when using mobile android.
